apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 2
  selector:
    matchLabels:
      abc: example
  template:
    metadata:
      labels:
        abc: example
    spec:
      containers:
        - name: c1
          image: mantu910/example:latest
          ports:
            - containerPort: 8081
